/*
create table person
(
    id integer not null,
    name varchar(255) not null,
    location varchar(255),
    birth_date timestamp,
    primary key(id)
);
 */

INSERT INTO PERSON(ID, NAME, LOCATION, BIRTH_DATE) VALUES(10001, 'YAKUP', 'ISTANBUL', CURRENT_TIMESTAMP());
INSERT INTO PERSON(ID, NAME, LOCATION, BIRTH_DATE) VALUES(10002, 'GUILLERMO', 'MADRID', CURRENT_TIMESTAMP());
INSERT INTO PERSON(ID, NAME, LOCATION, BIRTH_DATE) VALUES(10003, 'SWEN', 'AMSTERDAM', CURRENT_TIMESTAMP());
INSERT INTO PERSON(ID, NAME, LOCATION, BIRTH_DATE) VALUES(10004, 'SWEN', 'BERLIN', CURRENT_TIMESTAMP());